version: '3'
services:
  elasticseash:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.1"
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      #ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch
  logstash:
    image: "docker.elastic.co/logstash/logstash:7.15.1"
    build: .
    container_name: logstash
    volumes:
        #- ./:/usr/share/logstash/pipeline/
        - ./pipeline/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
    command: logstash -f /etc/logstash/conf.d/logstash.conf 
    networks:
      - elastic
    depends_on:
      - elasticsearch
    # command: >
    #     logstash -f /etc/logstash/conf.d/logstash.conf 
    #     && curl https://jdbc.postgresql.org/download/postgresql-42.2.8.jar -o /home/tnvan/
    #     && bin/logstash-plugin install logstash-input-jdbc

networks:
  elastic:
    driver: bridge